### PR TITLE
Add playhead visualisation to samplepolyline component

### PR DESCRIPTION
**Pull request by philipbelesky**
Alright, I think this is ready for some feedback. The implementation looks like:

https://user-images.githubusercontent.com/495961/136678388-0bd5b4f1-80a2-489b-98c3-849e832bf7dd.mov

I have a grab bag of notes:

- Both `AudioOutComponent` and `SampleToPolylineComponent` have 'cached' paths for their solves that only update the playhead. This seems to work well and both solve well under the `100ms` value I set as the playhead tracker update interval
- In `AudioOutComponent` I spent a while trying to properly add and draw the new output parameter by following the existing methods, but there was something going on with the stacking/Z-order that I don't understand. Are you able to take a look at this? I'm unfamiliar with most of this sort of custom UI code.
- There is a magic number `latencyCompensation` that I've used to improve the visual tracking of the playhead against the sound. I'd be interested to hear what this looks like on your system - I'm developing inside a Windows VM so might have more severe latency. 
    - I don't think the playhead needs to super-precisely track the sound to be useful, but if it's way off / too variable across systems then it might be not worth pursuing this feature
    - It could also be that I'm calculating the duration of the file incorrectly (possibly due to sampling rate?) as the playhead seems to 'start' at the right time. 
- Having the current playtime exposed numerically could be quite useful, e.g. using it downstream to trigger other playbacks 
- The playhead as a vanilla `Line` is pretty boring, perhaps its worth overriding the preview drawing method to make something fancier?

### CODE REVIEW

**Comment by AlasdairMott** [comment]
Its working but the wave doesn't look right for me any more - I think the caching is preventing me from updating the resolution? There is also some funny business with the player but that was probably there before.
Animation1

> In AudioOutComponent I spent a while trying to properly add and draw the new output parameter

Yeah I think I will redo most of that code. I learnt lots from your wave selector that I can apply to the player ui. I'll definitely need the 'cached' for this.

> magic number latencyCompensation

I wonder if the magic number will still work on longer files or if it will gradually drift out of sync.

> calculating the duration of the file incorrectly

I've noticed something that keeps popping up for me is I read the time as twice as long as the file is. Maybe something to do with that.

> Having the current playtime exposed numerically could be quite useful

Would ```owner.Wave.CurrentTime``` work for this?

>  using it downstream to trigger other playbacks

I'll have to think about how this would work... at the moment everything is precalculated, and only the user can trigger playback . Precise timing can be tricky in an environment like Grasshopper.

I think rather than have the wave to polyline component draw the playhead, a user is more likely to want to see how the geometry that created the sound is progressing. In that case I think the most important thing is just providing the %played (which can be converted into seconds quite easily) is enough.
Animation2

**Comment by philipbelesky** [comment]
> Its working but the wave doesn't look right for me any more - I think the caching is preventing me from updating the resolution? 

I think that might be due to an index mismatch from the addition of a `GetData` for Resolution on `main`. Altering resolution seems to work for me having merged `main` back into the PR branch.

> I'll have to think about how this would work... at the moment everything is precalculated, and only the user can trigger playback . Precise timing can be tricky in an environment like Grasshopper.

Yea, I guess in any case where the timing needs to be precise you'd always want to use a `Mixer` to ensure things are synced up. A bit of semi-random swing could be worth it for being able to control parameters in response to the playhead. `Data Dams` could be a lot of fun.

> I think rather than have the wave to polyline component draw the playhead, a user is more likely to want to see how the geometry that created the sound is progressing. In that case I think the most important thing is just providing the %played (which can be converted into seconds quite easily) is enough.

My thought is that while % played makes most sense as the control parameter in terms of data representation, having an interval with `current`/`total` potentially provides a quick bit of useful information as well as the ability to do both absolute and relative checks against play time. 

> Would owner.Wave.CurrentTime work for this?

I don't seem to find a CurrentTime property on that object or any of the other objects, but there might be a better solution below.

> I wonder if the magic number will still work on longer files or if it will gradually drift out of sync.
> I've noticed something that keeps popping up for me is I read the time as twice as long as the file is. Maybe something to do with that.

This [thread here](https://github.com/naudio/NAudio/issues/489) was useful - there's both a target latency to compensate for but also an interface that can provide a more accurate read. I think [this line](https://github.com/AlasdairMott/Siren/pull/11/files#diff-24aaed8c64f5ccb0f4e8a7a49ead01ec1d64bede6eba75de669f10a64bb57a4eR72) just needs to change the denominator to correctly get the total bytes of the wave in order to get an actual playstate rather than guessing via the tick rate. That change is probably very trivial to figure out but working on a teletype/grid project has sapped me of my ability to think this evening.

**Comment by AlasdairMott** [comment]
> current/total

good thinking! yeah that gives that little bit extra info. You know how on some gh inputs there is the option to modify the way its read, e.g radians and degrees, is there a way to do that for outputs? That way it could be user specified.

> don't seem to find a CurrentTime

That dissapeared when I changed wavegoo to cachedwavegoo... oops. On the mixer we could give it a publicly accessible wave which we set like this (line 200)
```
this.Wave = owner.Wave.ToRawSourceWaveStream();
owner.Mixer.AddMixerInput(wave);
```
and access from the audio out component
```
var mixerWave = (m_attributes as CustomGHButton).Wave;
var time = Wave.CurrentTime;
```

> working on a teletype/grid project

I love the teletype :)

**Comment by philipbelesky** [comment]
Ah, thanks, adding it to the attributes makes sense. I'm not sure about the `ToRawSourceWaveStream()`though - is this a new method to add to `CachedSound`? I had a look through the `NAudio` code but couldn't find anything similar. From what I can tell the `WaveStream` in the constructor of `CachedSound` isn't kept around after being made into `AudioData`. I haven't had a proper read through the NAudio docs yet so I think I'm missing something obvious.

**Comment by AlasdairMott** [comment]
Sorry ```ToRawSourceWaveStream()``` was only added in #16. I also exposed Position, Length and CurrentTime in the ```CachedSoundSampleProvider``` so you should be able to get it from there now

**Comment by philipbelesky** [comment]
Ah, great, I've implemented the method and it seems to track nicely and without drift over larger files. 

I've also had a go at re-writing the button code to try and minimise the amount of layout overrides so that the component is more resilient to changes in view settings. At the same time I've had a go a trying to make the button itself more similar to 'standard' Grasshopper buttons and the Oscillator UI. What did you think? 

https://user-images.githubusercontent.com/495961/137106932-38de3474-03c6-4ff4-b7cc-8b3b51d385b5.mov

Note that currently there's a TODO on line 217 of the `AudioOutComponent` relating to stopping the audio mid playback. Stopping the wave directly works, but subsequent plays then don't work. Does the mixer need to be controlled instead?

**Comment by AlasdairMott** [comment]
> seems to track nicely and without drift over larger files.

Brilliant!

I'd like to keep the player with lots of clickable area so that it can be easily moved around to the sound source. It looks like the other buttons have a largish blank area for this reason. Though I agree the button should be made more 'grasshoppery'. Looks like those buttons use the black scheme for the button part of the component.

click

It could be more like this?

image

>  Stopping the wave directly works, but subsequent plays then don't work

I think all you need to do is add this after line 216. As far as I know when you add a wavestrean to the mixer, it will go ahead and play that stream to the end, unless you remove it early.

```
owner.Mixer.RemoveAllMixerInputs();
```

**Comment by philipbelesky** [comment]
Alright, I am learning a lot about drawing in .Net! And becoming very nostalgic for CSS.

I've reimplemented the play/stop icons procedurally as I think that's the only way to get nice Grasshopper-native details without aliasing issues. They're pretty close to what you mocked up (and the native button). The slight edge rounding is the detail I've put in the 'too hard' bucket for now.

https://user-images.githubusercontent.com/495961/137309162-06483e13-464e-4409-b5c8-836538efe55d.mov

In locating the button and making space for grab/drags I tried a few layout options. If the output parameter label is being rendered, having it right-aligned looked odd to my eyes, so I've settled on centred. But if you want to try it out, you can edit line 148 and the `dragSpace` / `buttonWidth` variables to suit. 

The 'depressed' icon state is pretty lackluster - on the proper `Button` component the gradient inverts/recesses but this doesn't seem to be a convenient `GH_Palette` option, so I went with the standard 'selected green' colour. 

The component itself is also selected whenever the button is clicked, but that was in the original implementation. I've got no idea how to prevent this, but could ask around — I assume this is an unintended behaviour?

**Comment by AlasdairMott** [comment]
Works perfectly, nice one 💯 .  Rounding is actually super easy, for the pen constructors just do this:
``` using (var outerstroke = new Pen(Color.Black, 4f) { LineJoin = LineJoin.Round })```
I just edited it on your branch and it looks great.

I think centered looks right for now too. It might change a little anyway when we add stereo playback. The depressed state is so brief I didn't even notice it.

I hadn't noticed it was being selected. I guess it's only an issue when you click and drag it using the playhead.
click1

**Pull request merged**
