### PR TITLE
Add inline waveform icons

### PR DESCRIPTION
**Pull request by philipbelesky**
This is a draft PR for #4. To finish, I'll need to do a little research to figure out how to actually add inline images and the documentation for doing this sort of UI work is pretty sparse. At the moment I only know how to add buttons, which I've used as a placeholder (although they do set state correctly).

Screen Shot 2021-10-06 at 7 21 27 pm

Also, let me know if you have any issues with the below code - I've tried to keep the custom `GH_ComponentAttributes` decoupled from this particular component, but the abstractions might be more clunky than needed.

### CODE REVIEW

**Comment by philipbelesky** [comment]
Actually, scratch that, drawing images turned out to be pretty easy (`graphics.DrawImage(iconImages[i], iconBounds[i]);`)

Screen Shot 2021-10-06 at 7 53 14 pm

If the general design works for you, I'll fix up the icon spacing, add some sort of dimmed/gray state indicator, and put in some proper icons.

**Comment by AlasdairMott** [comment]
That looks really good. I'll need to fix up that icon as there is some weird aliasing going on.
image

>  I've tried to keep the custom GH_ComponentAttributes decoupled

I think that's a good idea, we can use the same attributes for an LFO component

**Comment by AlasdairMott** [comment]
Yep that makes sense. I've been modifying it a bit to get the in line version, which won't have that issue. - here's where I'm at

image

And the goal.

image

Eventually I'd like to try making the dial but for now the switch is only a minor change to #7

**Comment by philipbelesky** [comment]
Yea, that definitely looks better!

**Comment by AlasdairMott** [comment]
You did the hard part :) Changes are in #10 but some parts a little hacky (The way I'm reading the RespondToMouseDown event in a round about way). Can improve in this later though.

What do you think of A vs B vs C?
image

**Comment by philipbelesky** [comment]
Definitely B or C. I'm probably leaning towards C as the green of B is a little too neon to my eyes. Even if the color is tweaked, there is probably also an issue in that the selected icon would be very hard to see when the component itself is selected?

**Comment by AlasdairMott** [comment]
C it is

**Pull request merged**
